### ISSUE TITLE
Address port doesn't match id port

### ISSUE THREAD

**Issue by davidmarkclements** [upringjs/upring#14]
At least in the logs, I get this message:

```json
{"pid":96720,"hostname":"Davids-MacBook-Pro.local","level":30,"time":1483919160005,"msg":"node up","address":{"address":"192.168.0.6","family":"IPv4","port":51373},"id":"192.168.0.6:56225","v":1}
```

Note that port prop differs to port in id prop

Assuming base swim on port 3000, the following produces above output:

```js
const {execSync} = require('child_process')
const upring = require('upring')({
  base: [`${execSync('ipconfig getifaddr en0').toString().trim()}:3000`],
  hashring: {
    replicaPoints: 100,
    joinTimeout: 200
  }
})
```

**Comment by mcollina** [comment]
One is the TCP port used for tentacoli, and the other is the UDP port for SWIM (this is the one in the id).

**Comment by davidmarkclements** [comment]
Ah I see - perhaps we could make the long message more explicit? Though, not a high priority

**Comment by mcollina** [comment]
what would be a better log message?
