### ISSUE TITLE
Is UpRing Consistent or Available?

### ISSUE THREAD

**Issue by svaraborut** [upringjs/upring#22]
Sorry me for pointing this as an issue, but IMHO is a leak of information.

I read that upring may be used as base for a KV store or a basic Actor system.

But a statefull Actor system requires an AT_MOST_ONE message delivery and a consistent KV store need a unique write node for a given Key.

Reading through source code I see the that swim-hashring do not use any leader nor distributed confirmation/state signature system; therefore I assume that till cluster reaches convergence; different nodes may allocate same key to different nodes, and those nodes may accept it at the same time. If so the sistem opts for availability over consistency, is it true?

**Comment by mcollina** [comment]
UpRing is a generic mechanism to implement AP systems.

Convergence happens in a very short period of time, and there are hooks and APIs to resolve the conflicts if they arises.
