### ISSUE TITLE
Get notified by the stolen keys?

### ISSUE THREAD

**Issue by behrad** [upringjs/upring#31]
Is there any chance a node can be notified of responsible/incoming keys (when a peer goes down) @mcollina ?

`steal` event doesn't provide specific keys.
`.replica(key)` isn't being called consistently, or i don't know the correct semantics.

**Comment by mcollina** [comment]
I'm not really maintaining this atm. I'm happy to land a PR if you find a solution.

**Comment by behrad** [comment]
Can you give me any hints if this is really possible and where to look at @mcollina ?

**Comment by behrad** [comment]
This was my mistake misusing `.replica`.
